SELECT 'DROP TABLE ' || TABLE_NAME || ';'
   FROM ALL_TABLES
   WHERE TABLESPACE_NAME = 'USERS'
     AND TABLE_NAME IN(SELECT TABLE_NAME
                       FROM ALL_TABLES
                       WHERE TABLESPACE_NAME = 'USERS')
;
