INSERT INTO grade (num_curso,cod_disc) VALUES (3,23);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,20);
INSERT INTO grade (num_curso,cod_disc) VALUES (3,3);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,14);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,9);
INSERT INTO grade (num_curso,cod_disc) VALUES (3,6);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,26);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,12);
INSERT INTO grade (num_curso,cod_disc) VALUES (3,27);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,14);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,11);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,1);
INSERT INTO grade (num_curso,cod_disc) VALUES (3,9);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,7);
INSERT INTO grade (num_curso,cod_disc) VALUES (3,6);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,11);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,23);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,4);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,13);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,20);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,14);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,18);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,11);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,11);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,18);
INSERT INTO grade (num_curso,cod_disc) VALUES (3,15);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,19);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,3);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,20);
INSERT INTO grade (num_curso,cod_disc) VALUES (3,3);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,5);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,8);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,6);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,22);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,13);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,14);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,2);
INSERT INTO grade (num_curso,cod_disc) VALUES (2,26);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,23);
INSERT INTO grade (num_curso,cod_disc) VALUES (1,11);


-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,8);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,10);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,4);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,21);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,22);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,2);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,30);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,25);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,24);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,12);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,14);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,17);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,25);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,15);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,15);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,15);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,14);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,30);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,10);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,10);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,25);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,15);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,10);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,20);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,22);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,24);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,30);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,18);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,23);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,23);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,1);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,4);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,26);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,11);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,27);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,24);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,26);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,29);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,16);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,13);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,5);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,3);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,5);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,6);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,13);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,18);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,1);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,9);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,6);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,21);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,23);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,20);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,19);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,6);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,6);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,12);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (1,19);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,11);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (3,28);
-- INSERT INTO grade (num_curso,cod_disc) VALUES (2,27);