INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (1,'Benjamin','25/05/1987','americana',2,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (2,'Ayanna','16/12/1990','hortolandia',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (3,'Jonah','27/02/1996','indaiatuba',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (4,'Bethany','21/09/1989','hortolandia',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (5,'Ulla','30/11/1991','sao paulo',3,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (6,'Lucius','29/01/1988','americana',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (7,'Ulric','12/10/1988','taquarituba',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (8,'Davis','30/08/1986','americana',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (9,'Inez','30/04/1990','americana',3,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (10,'Hammett','04/10/1994','americana',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (11,'Jade','16/08/1993','indaiatuba',1,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (12,'Chava','11/12/1986','sao paulo',3,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (13,'May','17/05/1991','hortolandia',2,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (14,'Dane','12/02/1993','taquarituba',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (15,'Yael','05/05/1988','americana',3,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (16,'Nero','08/11/1997','hortolandia',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (17,'Slade','14/12/1995','indaiatuba',1,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (18,'Ora','18/10/1986','sao paulo',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (19,'Gavin','23/12/1995','taquarituba',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (20,'April','28/01/1995','taquarituba',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (21,'Velma','08/04/1994','sao paulo',2,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (22,'Gray','12/12/1994','taquarituba',1,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (23,'Jeremy','25/05/1994','campinas',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (24,'Ivy','17/06/1995','campinas',3,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (25,'Harrison','24/07/1998','sao paulo',2,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (26,'Dahlia','27/12/1996','campinas',2,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (27,'Brenden','14/11/1986','campinas',3,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (28,'Briar','06/12/1995','sao paulo',3,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (29,'Emery','16/11/1988','taquarituba',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (30,'Callum','13/12/1987','americana',1,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (31,'Harding','05/05/1997','indaiatuba',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (32,'Winifred','28/07/1986','hortolandia',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (33,'Lewis','09/03/1998','sao paulo',1,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (34,'Hunter','10/06/1992','indaiatuba',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (35,'Ursa','25/03/1994','sao paulo',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (36,'Jermaine','28/10/1990','hortolandia',3,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (37,'Hermione','25/04/1996','indaiatuba',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (38,'Kathleen','04/02/1992','indaiatuba',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (39,'Yuli','29/06/1998','campinas',3,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (40,'Valentine','10/08/1986','sao paulo',3,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (41,'Melinda','01/03/1995','taquarituba',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (42,'Wendy','31/10/1985','hortolandia',1,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (43,'Ronan','27/12/1987','indaiatuba',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (44,'Chaney','07/05/1996','americana',2,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (45,'Xander','07/12/1998','sao paulo',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (46,'Evelyn','06/03/1985','taquarituba',3,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (47,'Indira','03/11/1995','americana',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (48,'Glenna','26/12/1985','americana',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (49,'Josephine','05/06/1998','taquarituba',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (50,'Madison','21/04/1995','hortolandia',3,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (51,'Buffy','16/07/1995','campinas',2,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (52,'Ivory','25/05/1989','americana',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (53,'Charlotte','19/10/1994','taquarituba',1,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (54,'Peter','26/11/1994','indaiatuba',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (55,'Pamela','28/06/1996','campinas',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (56,'Coby','31/08/1993','indaiatuba',1,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (57,'Ori','29/03/1998','indaiatuba',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (58,'Stewart','05/10/1990','sao paulo',2,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (59,'Avram','22/10/1991','sao paulo',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (60,'David','09/07/1988','sao paulo',1,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (61,'Philip','03/09/1987','campinas',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (62,'Callum','15/01/1985','taquarituba',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (63,'Kenyon','28/09/1992','indaiatuba',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (64,'Dieter','24/08/1996','americana',1,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (65,'Jerry','23/02/1997','indaiatuba',1,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (66,'Chava','26/07/1993','campinas',3,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (67,'Jaquelyn','15/11/1998','hortolandia',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (68,'Lisandra','10/11/1997','americana',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (69,'Jordan','03/03/1987','sao paulo',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (70,'Wyatt','22/02/1994','taquarituba',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (71,'Thor','16/07/1994','americana',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (72,'Micah','04/01/1991','taquarituba',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (73,'Amity','16/04/1992','indaiatuba',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (74,'Josiah','04/01/1995','sao paulo',1,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (75,'Xandra','17/06/1988','americana',1,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (76,'Brenden','30/06/1994','hortolandia',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (77,'Aquila','27/08/1989','sao paulo',2,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (78,'Wyatt','12/07/1991','taquarituba',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (79,'Francesca','18/11/1985','indaiatuba',3,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (80,'Vivian','25/06/1987','americana',2,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (81,'Keely','22/10/1988','americana',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (82,'Mason','18/09/1991','campinas',3,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (83,'Deacon','01/10/1987','taquarituba',3,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (84,'Drew','02/02/1989','campinas',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (85,'Scarlet','01/05/1997','indaiatuba',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (86,'Zia','29/01/1994','hortolandia',3,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (87,'Alma','07/01/1997','taquarituba',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (88,'Quynn','11/11/1990','taquarituba',2,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (89,'Daryl','06/09/1988','americana',1,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (90,'Upton','20/07/1991','sao paulo',1,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (91,'Ima','30/08/1990','indaiatuba',3,'tobar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (92,'Ora','18/10/1993','sao paulo',2,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (93,'Rinah','14/02/1988','taquarituba',3,'nakamiti');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (94,'Byron','17/03/1998','americana',3,'patricia');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (95,'Joshua','28/01/1987','campinas',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (96,'Tyler','09/08/1987','sao paulo',1,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (97,'Brenden','05/03/1986','taquarituba',3,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (98,'Rhiannon','22/06/1992','taquarituba',2,'edmar');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (99,'Basia','26/02/1998','hortolandia',1,'dani');
INSERT INTO alunos_pos (ra,nome,data_nasc,cidade,num_curso,orientador) VALUES (100,'Trevor','05/12/1986','indaiatuba',2,'dani');