INSERT INTO disciplinas (cod,nome,creditos) VALUES (1,'calculo1',2);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (2,'calculo2',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (3,'calculo3',2);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (4,'calculo4',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (5,'fisica1',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (6,'fisica2',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (7,'fisica3',2);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (8,'apca',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (9,'apcb',2);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (10,'eda',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (11,'edb',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (12,'banco de dados a',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (13,'analise de algoritmos',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (14,'programacao',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (15,'poo',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (16,'paradigmas de programacao',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (17,'topicos de engenharia',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (18,'engenharia de software',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (19,'introducao a programacao',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (20,'introducao a computacao',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (21,'quimica',3);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (22,'tcc a',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (23,'tcc b',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (24,'estagio a',2);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (25,'estagio b',2);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (26,'gestao',2);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (27,'so a',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (28,'so b',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (29,'redes a',1);
INSERT INTO disciplinas (cod,nome,creditos) VALUES (30,'redes b',2);